refactor UpdateDrawFrame()
MisakaXiang/Raylib-Games pull request #2
Opened 2021-08-17 10:47 UTC by MisakaXiang

重构了update game()函数和drawgame()函数

2021-08-17 11:38 UTC, KarKLi requested changes
整体已经有了封装的思想，也对结构做出了不错的整理，还是有一些编程细节和规范需要修正。

2021-08-17 11:38 UTC, KarKLi commented on attr.h
> +    // bool canJump;
如果不需要的变量就把它删掉，不要注释留着。

2021-08-17 11:38 UTC, KarKLi commented on attr.h
> +    // int blocking;
同上

2021-08-17 11:38 UTC, KarKLi commented on file.h
> +        return -1;
这里是不是应该返回定义好的错误码？

2021-08-17 11:38 UTC, KarKLi commented on game.c
>          cameraUpdaters[cameraOption](&camera, &player, envBlocks, envItemsLength, deltaTime, screenWidth, screenHeight);
这里对cameraOption的操作不透明，在哪里给cameraOption进行了赋值呢？

2021-08-17 11:38 UTC, KarKLi commented on game.c
>      if (interface == 5)
interface的意义依然不明，interface的各种取值分别代表什么含义？是不是可以用enum来改成更容易理解的枚举。

2021-08-17 11:38 UTC, KarKLi commented on graphics.c
> +    for (int i = 0; i < note_num; i++)
这里为什么要分拆出两个一模一样的循环，是因为前面的循环一定要先把所有的souls都先遍历完才能执行第二个循环吗？

2021-08-17 11:38 UTC, KarKLi commented on graphics.c
> +        //DrawTextureRec(build_tex[num], envBlocks[i].rect, (Vector2){envBlocks[i].rect.x - build_tex[num].width * 0.01/2, envBlocks[i].rect.y - build_tex[num].height * 0.01/2}, WHITE);
不需要用的语句可以删掉哦。

2021-08-17 11:38 UTC, KarKLi commented on updateplayer.c
> +    if (!GameOver)
这里可以用卫语句的方式减少圈复杂度。
卫语句：尽早返回，比如这里，可以写成
```
if (GameOver) return;

// your business
```

2021-08-17 11:38 UTC, KarKLi commented on updateplayer.c
> +        CheckIfJumpOnBlocks(player, envBlocks, &JumpOnBlocks, delta);
这里可以把你这一系列操作的思路作为注释进行记录，方便你之后回看代码。

2021-08-17 11:38 UTC, KarKLi commented on updateplayer.c
> +        /* ???
这个如果不是你写的，可以和作者确认一下。

2021-08-17 11:38 UTC, KarKLi commented on updateplayer.h
> +// 判断 player 是否跑到最后一个音符, 若是, 停止播放音乐, 回到结束界面
函数注释一开始要写函数名。

2021-08-17 11:38 UTC, KarKLi commented on updateplayer.h
> +        if ((pPlayer->position.x >= (*pEnvBlocks)[i].rect.x) && (pPlayer->position.x <= (*pEnvBlocks)[i].rect.x + (*pEnvBlocks)[i].rect.width))
太长了，建议拆成两行。

2021-08-17 11:38 UTC, KarKLi commented on updateplayer.h
> +        if (CheckCollisionRecs(pPlayer->rect, (*pEnvBlocks)[i].rect) && (pPlayer->position.y > (*pEnvBlocks)[i].rect.y) && (on_build != i))
这个函数的命名我没有很理解，Recs是什么

2021-08-17 11:38 UTC, KarKLi commented on updateplayer.h
> +    for (int i = 0; i < note_num; i++)
这是事后结算吗？我看updateplayer.h是处理每一帧数据的，处理每一帧都要花费O(note_num)的时间复杂度是不是颇高了？

2021-08-17 11:38 UTC, KarKLi commented on updateplayer.h
> +void CheckIfSoulsEnd(Player *pPlayer, Soul **pSouls)
.h最好放函数签名，实现放到.c里面去。

2021-08-17 11:38 UTC, KarKLi commented on updateplayer.h
> +// updateplayer.h 用于处理player每一帧逻辑的头文件
.h内的所有的函数几乎没有对指针做判空操作。

2021-08-17 11:38 UTC, KarKLi commented on updateplayer.h
> +        int dis = (pPlayer->rect.x - (*pSouls)[i].rect.x) * (pPlayer->rect.x - (*pSouls)[i].rect.x) + (pPlayer->rect.y - (*pSouls)[i].rect.y) * (pPlayer->rect.y - (*pSouls)[i].rect.y);
表达式太长，增加几个中间变量来增强这个表达式的表达能力，如果存在多个这样的计算，将其封装为函数，更为直观易懂。

2021-08-17 11:38 UTC, KarKLi commented on updateplayer.h
> +        if (ei->rect.x <= p->x &&
可以写一下判断逻辑的注释。

2021-08-17 11:38 UTC, KarKLi commented on updateplayer.h
> +    for (int i = 0; i < note_num; i++)
是否可以有更高效的搜索方法？

2021-08-20 10:39 UTC, MisakaXiang commented on attr.h
> +    // bool canJump;
Done

2021-08-20 10:39 UTC, MisakaXiang commented on attr.h
> +    // int blocking;
Done

2021-08-20 10:39 UTC, MisakaXiang commented on file.h
> +        return -1;
Done

2021-08-20 10:39 UTC, MisakaXiang commented on game.c
>          cameraUpdaters[cameraOption](&camera, &player, envBlocks, envItemsLength, deltaTime, screenWidth, screenHeight);
camera.h里

2021-08-20 10:39 UTC, MisakaXiang commented on game.c
>      if (interface == 5)
Done

2021-08-20 10:39 UTC, MisakaXiang commented on updateplayer.h
> +void CheckIfSoulsEnd(Player *pPlayer, Soul **pSouls)
Done

2021-08-20 10:39 UTC, MisakaXiang commented on updateplayer.h
> +// updateplayer.h 用于处理player每一帧逻辑的头文件
Done

2021-08-20 10:39 UTC, MisakaXiang commented on updateplayer.h
> +        int dis = (pPlayer->rect.x - (*pSouls)[i].rect.x) * (pPlayer->rect.x - (*pSouls)[i].rect.x) + (pPlayer->rect.y - (*pSouls)[i].rect.y) * (pPlayer->rect.y - (*pSouls)[i].rect.y);
Done

2021-08-20 10:40 UTC, MisakaXiang commented on updateplayer.h
> +        if (ei->rect.x <= p->x &&
Done

2021-08-20 10:40 UTC, MisakaXiang commented on updateplayer.h
> +    for (int i = 0; i < note_num; i++)
Done

2021-08-20 10:40 UTC, MisakaXiang commented on graphics.c
> +    for (int i = 0; i < note_num; i++)
合并到一起了

2021-08-20 10:40 UTC, MisakaXiang commented on updateplayer.c
> +    if (!GameOver)
Done

2021-08-20 10:40 UTC, MisakaXiang commented on graphics.c
> +        //DrawTextureRec(build_tex[num], envBlocks[i].rect, (Vector2){envBlocks[i].rect.x - build_tex[num].width * 0.01/2, envBlocks[i].rect.y - build_tex[num].height * 0.01/2}, WHITE);
Done

2021-08-20 10:40 UTC, MisakaXiang commented on updateplayer.c
> +        CheckIfJumpOnBlocks(player, envBlocks, &JumpOnBlocks, delta);
Done

2021-08-20 10:40 UTC, MisakaXiang commented on updateplayer.c
> +        /* ???
Done

2021-08-20 10:40 UTC, MisakaXiang commented on updateplayer.h
> +// 判断 player 是否跑到最后一个音符, 若是, 停止播放音乐, 回到结束界面
Done

2021-08-20 10:41 UTC, MisakaXiang commented on updateplayer.h
> +        if ((pPlayer->position.x >= (*pEnvBlocks)[i].rect.x) && (pPlayer->position.x <= (*pEnvBlocks)[i].rect.x + (*pEnvBlocks)[i].rect.width))
Done

2021-08-20 10:41 UTC, MisakaXiang commented on updateplayer.h
> +        if (CheckCollisionRecs(pPlayer->rect, (*pEnvBlocks)[i].rect) && (pPlayer->position.y > (*pEnvBlocks)[i].rect.y) && (on_build != i))
是他的库函数，判断两个rectangle是否相撞

2021-08-20 10:43 UTC, MisakaXiang commented on updateplayer.h
> +    for (int i = 0; i < note_num; i++)
用了一个变量来辅助查找，但是还是O(note_num)的复杂度，不知道怎么改了

2021-08-20 14:38 UTC, KarKLi requested changes
整体还有一些代码比较复杂的地方需要简化，性能可以尝试着进一步提升，使用记忆化搜索的方法，避免每次都搜索整个数组，数组本身是否存在一些有序？或者玩家的行为是否具有单向性？

2021-08-20 14:38 UTC, KarKLi commented on game.c
>  void UpdateGame(void)
对于有限状态机的优化，可以使用表驱动的方式来更新有限状态机的状态。可以思考一下，对于该有限状态机的每个状态来说，其输入状态和输出状态是否可以整合为一个统一的函数签名？
函数签名是否可以描述有限状态机中节点的特征呢？

2021-08-20 14:38 UTC, KarKLi commented on game.h
> +
是否可以在该文件的开头注明这个文件是做什么的呢？

2021-08-20 14:38 UTC, KarKLi commented on graphics.c
> +        else if (souls[i].collect)
使用卫语句的方式可减少else-if数量，因为你三个条件全部都是互斥的，画完之后其实就可以直接return了

2021-08-20 14:38 UTC, KarKLi commented on interface.h
> +enum
可对该enum的每个字段都加以含义注释。

2021-08-20 14:38 UTC, KarKLi commented on updateplayer.c
> +int ComputeDistance(Player *pPlayer, Soul *pSouls)
函数注释。

2021-08-20 14:38 UTC, KarKLi commented on updateplayer.c
> +    CheckPointer(pPlayer);
checkPointer错误了之后后面的逻辑执行是会导致崩溃的，没有空指针对应的处理吗？

2021-08-20 14:38 UTC, KarKLi commented on memtools.h
>  void CheckPointer(void *ptr)
如果没有返回值，这个checkpointer打出来的错误信息完全没用。

2021-08-20 14:38 UTC, KarKLi commented on updateplayer.c
> +        if ((pPlayer->position.x >= (*pEnvBlocks)[i].rect.x) &&
我的理解是玩家是不断向前的，搜索左起点是否可以减少为上一次调用CheckIfGameOver时的i？或者说是否可以在别处记录上一次搜索到了哪个pEnvBlocks？

2021-08-20 14:38 UTC, KarKLi commented on updateplayer.c
> +void CheckIfJumpOnBlocks(Player *pPlayer, EnvItem **pEnvBlocks, int *JumpOnBlocks, float delta)
这个函数命名比较奇怪，If想表达的是“是否”，但是在这里用Can会不会更好些，更直观？

2021-08-20 14:38 UTC, KarKLi commented on updateplayer.c
> +    // pass_soul_index + 1 则为距离 player 最近的 soul 的索引
这里就使用了soul的索引来优化搜索，很好

2021-08-20 14:48 UTC, closed without merging